apiVersion: v2
name: promtail-stack
description: A Helm chart for Promtail log collector
version: 0.1.0
dependencies:
  - name: promtail
    version: 6.15.0
    repository: "https://grafana.github.io/helm-charts"
